Part 1

In [3]:
import requests, random
import gzip, json
import pandas as pd
from io import BytesIO

In [4]:
#2 step randomization (option1 discussed inclass)
#   2.1 - extract a random list of urls from dolma 
#   2.2 - filter out urls containing unsafe files (refinedweb ones)
#   2.3 - true random sampling of 15 urls to extract tokens from (next cell)

#full list of Dolma dataset files are here...
dolma_url_list = "https://huggingface.co/datasets/allenai/dolma/raw/main/urls/v1_7.txt"

#download url list via python request
resp = requests.get(dolma_url_list)
all_urls = resp.text.splitlines()  #break list into separate urls like [ 'https://url1', 'https://url2', ..., 'https://urln']

#filter out unsafe or unwanted sources
safe_urls = [u for u in all_urls if "falcon-refinedweb" not in u]

#randomly sample 15
sampled_urls = random.sample(safe_urls, 15)
# print("Selected urls:\n")
# for u in sampled_urls:
#     print(u)

In [ ]:
#2 step randomization (option1 discussed inclass)
#   2.5 - reading the same number of tokens from each file akin to RR (round robin)
#   2.6 - tag to record reading progress per file
#   2.7 - loop runs until the token_target is reached
token_target = 300000
token_count = 0
samples = []

#same amount of tokens to be grabbed from each sampled url
tokens_per_url = token_target // len(sampled_urls) 

#tag to record reading progress per file
progress_tracker = {url: 0 for url in sampled_urls}

#loop runs until the token_target is reached
while token_count < token_target:
    for url in sampled_urls:
        print(f"\nReading from: {url}")
        resp = requests.get(url, stream=True)
        resp.raise_for_status() #raise server side errors such as 404/500!

        with gzip.open(BytesIO(resp.content), "rt", encoding="utf-8") as f:
            for i, line in enumerate(f):
                if i < progress_tracker[url]:
                    continue  #skip lines already processed

                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    continue

                text = obj.get("text", "")
                metadata = obj.get("metadata", {})

                metadata_url = None

                #pull out the url field from the metadata dictionary 
                if isinstance(metadata, dict):
                    metadata_url = metadata.get("url", None)

                tokens = len(text.split())
                token_count += tokens

                #grab only the text + url fields from each row
                samples.append({
                    "text": text,
                    "url": metadata_url
                })

                progress_tracker[url] = i + 1  #update position (we read upto) IN FILE 

                #stop reading this file if it has reached its token limit
                if token_count >= token_target:
                    break
                if token_count // tokens_per_url > sampled_urls.index(url):
                    break  #move to next file once its share is done - 1 file cannot dominate the token sampling

        if token_count >= token_target:
            break

print(f"\nCollected {len(samples)} text samples from {token_count} tokens!")

Testing

In [ ]:
#view collected text
print("\nExtracted text samples\n")
for i, sample in enumerate(samples, 1):
    print(f"sample #{i}:\n{sample}\n\n")

Part 2

In [11]:
#sampled dolma text - use to answer Part 2 questions
df = pd.DataFrame(samples)
df.to_excel("dolma_samples_part2.xlsx", index=False)

Part 3 - constants

In [18]:
rand_sample_count = 10 # The number of random samples we want from our dataset
file_loc_ruddit="ruddit_comments_score.csv" #The file path to the data you want to sample
file_loc_dolma="dolma_samples_part2.xlsx"

Part 3.1 - Ruddit

In [19]:
the_sheet_name="ruddit_rand_samples_part3.xlsx" #The Excel Sheet name we want to have for our randum samples
rand_samples = []
rand_indices = []

data_ruddit=pd.read_csv(file_loc_ruddit,header=0)
data_ruddit = data_ruddit[data_ruddit["body"]!="[deleted]"] #Remove all of the samples that have [deleted] as their body text
data_ruddit.reset_index()

print(f"Total valid comments: {len(data_ruddit)}")
data_ruddit.head()

Total valid comments: 5744

  comment_id                                               body  score
0    cza1q49  > The difference in average earnings between m... -0.083
1    cza1wdh  The myth is that the "gap" is entirely based o... -0.022
3    cza2bw8  The assertion is that women get paid less for ... -0.146
4    cza2iji  You said in the OP that's not what they're mea... -0.083
5    cza2jj3  >Men and women are not payed less for the same... -0.042

In [20]:
min_index = data_ruddit.index.min()
max_index = data_ruddit.index.max()
used_indices = set()

while len(rand_indices) < rand_sample_count:
    sample_index = random.randint(min_index, max_index)

    if sample_index in used_indices:
        continue
    used_indices.add(sample_index)

    rand_indices.append(sample_index)

    id_val = data_ruddit["comment_id"].iloc[sample_index]
    text_val = data_ruddit["body"].iloc[sample_index]
    score_val = data_ruddit["score"].iloc[sample_index]

    rand_sample = {
        "comment_id": id_val,
        "text": text_val,
        "score": score_val
    }

    rand_samples.append(rand_sample)

samples_df_ruddit = pd.DataFrame(rand_samples)
samples_df_ruddit.to_excel(
    the_sheet_name,
    header=True,
    index=False
)

samples_df_ruddit

  comment_id                                               text  score
0    eg033tl  I don't have car. And I walked as much in Seou... -0.208
1    d3lfneg  Of course he would. He'd also end Obamacare, t...  0.479
2    eooegqj  I take great pride in assuming that *she'll* b... -0.021
3    e2s093n  Do you honestly think the new modding tools co... -0.208
4    eff52jy  Part of the issue is that the population of pa...  0.000
5    eem5dq3  She has more intelligence than you... hence wh...  0.104
6    dqcmkoy  Holy fucking Mary you don’t know anything abou...  0.917
7    czjex5r  There are six arguments that I believe make th... -0.021
8    cza8437  Absolutely. But "socialization" is not a monol...  0.042
9    e3ps4ik  Compassion isn't the GOP's thing. They like to... -0.125

Part 3.2 - Dolma

In [22]:
the_sheet_name_dolma = "dolma_rand_samples_part3.xlsx"   # output Excel file
rand_samples_dolma = []        # list to store the sampled dictionaries

data_dolma = pd.read_excel(file_loc_dolma,usecols="A:B")
data_dolma.reset_index()

total_row_count = data_dolma.count()
total_row_count = total_row_count["text"]
print(f"Total Rows = {total_row_count}")

max_index=data_dolma.index.max()
min_index=data_dolma.index.min()

Total Rows = 381

In [23]:
used_indices = set()

while len(rand_samples) < rand_sample_count:
    sample_index = random.randint(min_index, max_index)

    if sample_index in used_indices:
        continue
    used_indices.add(sample_index)

    print(f"sample_index={sample_index}")

    text_val = data_dolma["text"].iloc[sample_index]
    url_val = data_dolma["url"].iloc[sample_index]

    rand_sample = {
        "text": text_val,
        "url": url_val
    }

    rand_samples.append(rand_sample)
    
samples_df_dolma = pd.DataFrame(rand_samples)

samples_df_dolma.to_excel(
    the_sheet_name,
    header=True,
    index=False
)

samples_df_dolma

  comment_id                                               text  score
0    eg033tl  I don't have car. And I walked as much in Seou... -0.208
1    d3lfneg  Of course he would. He'd also end Obamacare, t...  0.479
2    eooegqj  I take great pride in assuming that *she'll* b... -0.021
3    e2s093n  Do you honestly think the new modding tools co... -0.208
4    eff52jy  Part of the issue is that the population of pa...  0.000
5    eem5dq3  She has more intelligence than you... hence wh...  0.104
6    dqcmkoy  Holy fucking Mary you don’t know anything abou...  0.917
7    czjex5r  There are six arguments that I believe make th... -0.021
8    cza8437  Absolutely. But "socialization" is not a monol...  0.042
9    e3ps4ik  Compassion isn't the GOP's thing. They like to... -0.125